# Generated by Django 5.0.7 on 2024-08-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='choice_text',
            new_name='comment_text',
        ),
    ]
