# Generated by Django 5.0.7 on 2024-08-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_page_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default="1970-01-01 00:00:00", verbose_name='date published'),
            preserve_default=False,
        ),
    ]
