# Generated by Django 5.0.7 on 2024-08-06 11:27

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_comment_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_text',
            field=mdeditor.fields.MDTextField(max_length=10000),
        ),
    ]
