# Generated by Django 5.0.7 on 2024-08-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_alter_page_page_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='author_name',
            field=models.CharField(default='TooMuchAgoToShow', max_length=50),
            preserve_default=False,
        ),
    ]
