# Generated by Django 5.0.7 on 2024-08-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_page_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='author_name',
        ),
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default='ToMuchAgoToShow', max_length=50),
            preserve_default=False,
        ),
    ]
